apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: apache
        image: apache
        ports:
        - containerPort: 80
